Fixxo.MVC/Controllers/CreateProductController.cs
using Fixxo.Core.Interface.Services;
using Fixxo.MVC.Models.InputDto;
using Microsoft.AspNetCore.Mvc;

namespace Fixxo.MVC.Controllers
{
    public class CreateProductController : Controller
    {
        // Mina produkter har en del, så create product får en egen controller , srp


        private readonly ICreateProductService _createProductService;


        public CreateProductController(ICreateProductService createProductService)
        {
            _createProductService = createProductService;
        }

        public IActionResult Create()
        {

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateProductInputDto dto)
        {
            await _createProductService.CreateAsync(dto.ToModel());

            return View();
        }
    }
}

Fixxo.MVC/Views/Shared/_FooterPartial.cshtml
<div class="background-lightgrey footer">
    <div class="footer-socialmedia">
        <i class="fa-brands fa-facebook-f"></i>
        <i class="fa-brands fa-instagram"></i>
        <i class="fa-brands fa-twitter"></i>
        <i class="fa-brands fa-google"></i>
        <i class="fa-brands fa-linkedin"></i>
    </div>
    <div class="footer-copyright">
        <p><i class="fa-regular fa-copyright"></i>2022 Fixxo. All Rights Reserved</p>
    </div>
</div>

Fixxo.MVC/Views/Shared/_HeaderPartial.cshtml
<header class="header-section">
    <div class="header-img-container">
        <div>
            <img src="/images/header-female.svg" alt="">
        </div>
        <div class="sale-div">
            <h1>SALE UP </h1>
            <h1>TO 50% OFF</h1>
            <p>Online shopping free home delivery over $100</p>
            <div class="red-box background-lightred">
                <div class="corner-container">
                    <div class="white-corner-div">
                        <div class="cover-div-1"></div>
                        <div class="cover-div-2"></div>
                    </div>
                </div>
                <div class="d-flex justify-content-center align-items-center">
                    <p class="pt-3"><strong>SHOP NOW</strong></p>
                </div>
                <div class="corner-container">
                    <div class="white-corner-reverse-div">
                        <div class="cover-reverse-div-1"></div>
                        <div class="cover-reverse-div-2"></div>
                    </div>
                </div>
            </div>
        </div>
        <div>
            <img src="/images/header-male.svg" alt="">
        </div>
    </div>
</header>

Fixxo.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Fixxo.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Fixxo.MVC.styles.css" asp-append-version="true" />
</head>
<body>


    <main>
        @RenderBody()
    </main>


    @* <footer class="border-top footer text-muted"> *@
    @*     <div class="container"> *@
    @*         &copy; 2022 - Fixxo.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> *@
    @*     </div> *@
    @* </footer> *@
    <script src="https://kit.fontawesome.com/470a8b5ff5.js" crossorigin="anonymous"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Fixxo.MVC/Views/Shared/_NavbarPartial.cshtml
<navbar class="nav-bar">
    <div>
        <img src="/images/logo.svg" asp-append-version="true" alt="logo">
    </div>
    <div>
        <a asp-controller="Home" asp-action="Index">Home</a>
        <a href="">Categories</a>
        <a asp-controller="CreateProduct" asp-action="Create">Create a product</a>
        <a asp-controller="Contacts" asp-action="Index">Contacts</a>

    </div>
    <div class="nav-icons-div">
        <div class="icon-circle">
            <i class="fa-solid fa-magnifying-glass"></i>
        </div>
        <div class="icon-circle">
            <i class="fa-solid fa-arrows-spin"></i>
        </div>
        <div class="icon-circle">
            <i class="fa-solid fa-cart-shopping"></i>
        </div>
        <div class="icon-circle">
            <i class="fa-solid fa-heart"></i>
        </div>
    </div>
</navbar>

<script src="https://kit.fontawesome.com/470a8b5ff5.js" crossorigin="anonymous"></script>