Fixxo.MVC/Controllers/DetailsSwitchController.cs
using Fixxo.Core.Interface.Services;
using Microsoft.AspNetCore.Mvc;

namespace Fixxo.MVC.Controllers
{
    public class DetailsSwitchController : Controller
    {

        // srp sköter switch för vilken details produkt. Den här switch kan potentiellt bli väldigt lång, så egen controller

        private readonly ICatalogItemService _catalogItemService;

        public DetailsSwitchController(ICatalogItemService catalogItemService)
        {
            _catalogItemService = catalogItemService;
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            var product = await _catalogItemService.GetAsync(id);

            // inte nöjd över den här lösningen. Nosql utan ef core hade nog varit bra men hinner inte läsa på och bygga det, så.....

            return product.Category switch
            {
                "Jacket" => RedirectToAction("Jacket", "DetailsProducts", new { id }),
                "Shoes" => RedirectToAction("Shoes", "DetailsProducts", new { id }),
                "Boots" => RedirectToAction("Boots", "DetailsProducts", new { id }),
                "High heels" => RedirectToAction("HighHeels", "DetailsProducts", new { id }),
                _ => RedirectToAction("Index", "Home")
            };
        }
    }
}

Fixxo.MVC/Views/Shared/ProductPartials/_4ProductsPartial.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model Fixxo.MVC.ViewModels.HomeIndexViewModel

<div class="four-products-h-grid">    
    <div class="grey-box-50 me-2 grid-item-1">

    </div>
    <section class="featured-product ms-2 grid-item-2">
        <div class="featured-grid featured-grid-4">

            @{
                if (Model != null)
                {
                    if (Model.Jackets.Count + Model.Shoes.Count + Model.Boots.Count + Model.HighHeels.Count < 5)
                    {
                        foreach (var jacket in Model.Jackets)
                        {
                            <partial name="ProductPartials/_JacketPartial" model="jacket" />
                        }

                        foreach (var shoes in Model.Shoes)
                        {
                            <partial name="ProductPartials/_ShoesPartial" model="shoes"/>
                        }


                        foreach (var boots in Model.Boots)
                        {
                            <partial name="ProductPartials/_BootsPartial" model="boots"/>
                        }

                        foreach (var highHeels in Model.HighHeels)
                        {
                            <partial name="ProductPartials/_HighHeelsPartial" model="highHeels" />
                        }
                    }
                    else
                    {
                        for (var i = 0; i < 4; i++)
                        {
                            foreach (var jacket in Model.Jackets)
                            {
                                if (i >= 4)
                                    break;
                                <partial name="ProductPartials/_JacketPartial" model="jacket" />
                                i++;
                                
                            }

                            foreach (var shoes in Model.Shoes)
                            {
                                if (i >= 4)
                                    break;
                                <partial name="ProductPartials/_ShoesPartial" model="shoes" />
                                i++;
                            }


                            foreach (var boots in Model.Boots)
                            {
                                if (i >= 4)
                                    break;
                                <partial name="ProductPartials/_BootsPartial" model="boots" />
                                i++;
                            }

                            foreach (var highHeels in Model.HighHeels)
                            {
                                if (i >= 4)
                                    break;
                                <partial name="ProductPartials/_HighHeelsPartial" model="highHeels"/>
                                i++;
                            }
                        }
                    }
                }
            }

        </div>
    </section>
</div>

Fixxo.MVC/Views/Shared/ProductPartials/_8ProductsPartial.cshtml
@model Fixxo.MVC.ViewModels.HomeIndexViewModel

<section class="featured-product">
    <div class="center-grid">
        <h2 class="pb-3">Featured Products</h2>
    </div>
    <div class="featured-grid">
        
        

        @{
            if (Model != null)
            {
                if (Model.Jackets.Count + Model.Shoes.Count + Model.Boots.Count + Model.HighHeels.Count < 9)
                {

                    foreach (var jacket in Model.Jackets)
                    {
                        <partial name="ProductPartials/_JacketPartial" model="jacket" />
                    }

                    foreach (var shoes in Model.Shoes)
                    {
                        <partial name="ProductPartials/_ShoesPartial" model="shoes"/>
                    }


                    foreach (var boots in Model.Boots)
                    {
                        <partial name="ProductPartials/_BootsPartial" model="boots"/>
                    }

                    foreach (var highHeels in Model.HighHeels)
                    {
                        <partial name="ProductPartials/_HighHeelsPartial" model="highHeels" />
                    }
                }
                else
                {
                    for (var i = 0; i < 8; i++)
                    {
                        if (Model != null)
                        {
                            foreach (var jacket in Model.Jackets)
                            {
                                if (i >= 8)
                                    break;
                                <partial name="ProductPartials/_JacketPartial" model="jacket"/>
                                i++;
                            }

                            foreach (var shoes in Model.Shoes)
                            {
                                if (i >= 8)
                                    break;
                                <partial name="ProductPartials/_ShoesPartial" model="shoes" />
                                i++;
                            }


                            foreach (var boots in Model.Boots)
                            {
                                if (i >= 8)
                                    break;
                                <partial name="ProductPartials/_BootsPartial" model="boots" />
                                i++;
                            }

                            foreach (var highHeels in Model.HighHeels)
                            {
                                if (i >= 8)
                                    break;
                                <partial name="ProductPartials/_HighHeelsPartial" model="highHeels" />
                                i++;
                            }
                        }
                    }
                }
            }
        }

    </div>
</section>

Fixxo.MVC/Views/Shared/ProductPartials/_BootsPartial.cshtml
@model Fixxo.MVC.Models.OutputDto.ShoesDto.GetBootsOutputDto


<div class="featured-box">
    <div class="featured-square">
        <div class="img-container">
            @{
                if (Model.ImgUrl != null)
                {
                    <img class="img" src="@Model.ImgUrl" alt="image" />
                }
                else
                {
                    <img class="img" src="/images/pexels-deden-dicky-ramdhani-5755160.jpg" alt="image" />
                }
            }
        </div>
        <div class="quick-view-icons">
            <div class="icon-circle">
                <a href="https://www.dn.se/"><i class="fa-solid fa-heart"></i></a>
            </div>
            <div class="icon-circle">
                <i class="fa-solid fa-arrows-spin"></i>
            </div>
            <div class="icon-circle">
                <i class="fa-solid fa-bag-shopping"></i>
            </div>

        </div>
        <div class="red-box">
            <div class="corner-container">
                <div class="white-corner-div">
                    <div class="cover-div-1"></div>
                    <div class="cover-div-2"></div>
                </div>
            </div>
            <div class="d-flex justify-content-center align-items-center">
                <p class="pt-3">QUICK VIEW</p>
            </div>
            <div class="corner-container">
                <div class="white-corner-reverse-div">
                    <div class="cover-reverse-div-1"></div>
                    <div class="cover-reverse-div-2"></div>
                </div>
            </div>
        </div>

    </div>
    <div class="featured-text">
        @if (Model != null)
        {
            <p>@Model.Category</p>
            <p><strong>@Model.Name</strong></p>
            <div>
                @for (var i = Model.Rating; i > 0; i--)
                {
                    <i class="fa-solid fa-star"></i>
                }
            </div>
            <p><strong>$@Model.Price</strong></p>
            <a asp-controller="DetailsSwitch" asp-action="Details" asp-route-id="@Model.CatalogItemId">Details</a>
        }

    </div>
</div>

Fixxo.MVC/Views/Shared/ProductPartials/_HighHeelsPartial.cshtml
@model Fixxo.MVC.Models.OutputDto.ShoesDto.GetHighHeelsOutputDto


<div class="featured-box">
    <div class="featured-square">
        <div class="img-container">
            @{
                if (Model.ImgUrl != null)
                {
                    <img class="img" src="@Model.ImgUrl" alt="image" />
                }
                else
                {
                    <img class="img" src="/images/pexels-deden-dicky-ramdhani-5755160.jpg" alt="image" />
                }
            }
        </div>
        <div class="quick-view-icons">
            <div class="icon-circle">
                <a href="https://www.dn.se/"><i class="fa-solid fa-heart"></i></a>
            </div>
            <div class="icon-circle">
                <i class="fa-solid fa-arrows-spin"></i>
            </div>
            <div class="icon-circle">
                <i class="fa-solid fa-bag-shopping"></i>
            </div>

        </div>
        <div class="red-box">
            <div class="corner-container">
                <div class="white-corner-div">
                    <div class="cover-div-1"></div>
                    <div class="cover-div-2"></div>
                </div>
            </div>
            <div class="d-flex justify-content-center align-items-center">
                <p class="pt-3">QUICK VIEW</p>
            </div>
            <div class="corner-container">
                <div class="white-corner-reverse-div">
                    <div class="cover-reverse-div-1"></div>
                    <div class="cover-reverse-div-2"></div>
                </div>
            </div>
        </div>

    </div>
    <div class="featured-text">
        @if (Model != null)
        {
            <p>@Model.Category</p>
            <p><strong>@Model.Name</strong></p>
            <div>
                @for (var i = Model.Rating; i > 0; i--)
                {
                    <i class="fa-solid fa-star"></i>
                }
            </div>
            <p><strong>$@Model.Price</strong></p>
            <a asp-controller="DetailsSwitch" asp-action="Details" asp-route-id="@Model.CatalogItemId">Details</a>
        }

    </div>
</div>

Fixxo.MVC/Views/Shared/ProductPartials/_JacketPartial.cshtml
@model Fixxo.MVC.Models.OutputDto.GetJacketOutputDto


<div class="featured-box">
    <div class="featured-square">
        <div class="img-container">
            @{
                if (Model.ImgUrl != null)
                {
                    <img class="img" src="@Model.ImgUrl" alt="image" />
                }
                else
                {
                    <img class="img" src="/images/pexels-deden-dicky-ramdhani-5755160.jpg" alt="image" />
                }
            }
        </div>
        <div class="quick-view-icons">
            <div class="icon-circle">
                <a href="https://www.dn.se/"><i class="fa-solid fa-heart"></i></a>
            </div>
            <div class="icon-circle">
                <i class="fa-solid fa-arrows-spin"></i>
            </div>
            <div class="icon-circle">
                <i class="fa-solid fa-bag-shopping"></i>
            </div>

        </div>
        <div class="red-box">
            <div class="corner-container">
                <div class="white-corner-div">
                    <div class="cover-div-1"></div>
                    <div class="cover-div-2"></div>
                </div>
            </div>
            <div class="d-flex justify-content-center align-items-center">
                <p class="pt-3">QUICK VIEW</p>
            </div>
            <div class="corner-container">
                <div class="white-corner-reverse-div">
                    <div class="cover-reverse-div-1"></div>
                    <div class="cover-reverse-div-2"></div>
                </div>
            </div>
        </div>

    </div>
    <div class="featured-text">
        @if (Model != null)
        {
            <p>@Model.Category</p>
            <p><strong>@Model.Name</strong></p>
            <div>
                @for (var i = Model.Rating; i > 0; i--)
                {
                    <i class="fa-solid fa-star"></i>
                }
            </div>
            <p><strong>$@Model.Price</strong></p>
            <a asp-controller="DetailsSwitch" asp-action="Details" asp-route-id="@Model.CatalogItemId">Details</a>
        }

    </div>
</div>

Fixxo.MVC/Views/Shared/ProductPartials/_ProductPartial.cshtml
@model Fixxo.MVC.Models.OutputDto.GetProductOutputDto

@* @model Fixxo.MVC.Interfaces.IGetDto *@

<div class="featured-box">
    <div class="featured-square">
        <div class="img-container">
        @{
            if (Model.ImgUrl != null)
            {
                    <img class="img" src="@Model.ImgUrl" alt="image"/>
            }
            else
            {
                    <img class="img" src="/images/pexels-deden-dicky-ramdhani-5755160.jpg" alt="image"/>
            }
        }
        </div>
        <div class="quick-view-icons">
            <div class="icon-circle">
                <a href="https://www.dn.se/"><i class="fa-solid fa-heart"></i></a>
            </div>
            <div class="icon-circle">
                <i class="fa-solid fa-arrows-spin"></i>
            </div>
            <div class="icon-circle">
                <i class="fa-solid fa-bag-shopping"></i>
            </div>

        </div>
        <div class="red-box">
            <div class="corner-container">
                <div class="white-corner-div">
                    <div class="cover-div-1"></div>
                    <div class="cover-div-2"></div>
                </div>
            </div>
            <div class="d-flex justify-content-center align-items-center">
                <p class="pt-3">QUICK VIEW</p>
            </div>
            <div class="corner-container">
                <div class="white-corner-reverse-div">
                    <div class="cover-reverse-div-1"></div>
                    <div class="cover-reverse-div-2"></div>
                </div>
            </div>
        </div>

    </div>
    <div class="featured-text">
        @if (Model != null)
        {
            <p>@Model.Category</p>
            <p><strong>@Model.Name</strong></p>
            <div>
                @for (var i = Model.Rating; i > 0; i--)
                {
                    <i class="fa-solid fa-star"></i>
                }
            </div>
            <p><strong>$@Model.Price</strong></p>
            <a asp-controller="DetailsSwitch" asp-action="Details" asp-route-id="@Model.CatalogItemId" >Details</a>
        }
        
        
       @* kan jag checka category här och göra anropet enklare? *@
        

    </div>
</div>

Fixxo.MVC/Views/Shared/ProductPartials/_ShoesPartial.cshtml
@model Fixxo.MVC.Models.OutputDto.ShoesDto.GetShoesOutputDto


<div class="featured-box">
    <div class="featured-square">
        <div class="img-container">
            @{
                if (Model.ImgUrl != null)
                {
                    <img class="img" src="@Model.ImgUrl" alt="image" />
                }
                else
                {
                    <img class="img" src="/images/pexels-deden-dicky-ramdhani-5755160.jpg" alt="image" />
                }
            }
        </div>
        <div class="quick-view-icons">
            <div class="icon-circle">
                <a href="https://www.dn.se/"><i class="fa-solid fa-heart"></i></a>
            </div>
            <div class="icon-circle">
                <i class="fa-solid fa-arrows-spin"></i>
            </div>
            <div class="icon-circle">
                <i class="fa-solid fa-bag-shopping"></i>
            </div>

        </div>
        <div class="red-box">
            <div class="corner-container">
                <div class="white-corner-div">
                    <div class="cover-div-1"></div>
                    <div class="cover-div-2"></div>
                </div>
            </div>
            <div class="d-flex justify-content-center align-items-center">
                <p class="pt-3">QUICK VIEW</p>
            </div>
            <div class="corner-container">
                <div class="white-corner-reverse-div">
                    <div class="cover-reverse-div-1"></div>
                    <div class="cover-reverse-div-2"></div>
                </div>
            </div>
        </div>

    </div>
    <div class="featured-text">
        @if (Model != null)
        {
            <p>@Model.Category</p>
            <p><strong>@Model.Name</strong></p>
            <div>
                @for (var i = Model.Rating; i > 0; i--)
                {
                    <i class="fa-solid fa-star"></i>
                }
            </div>
            <p><strong>$@Model.Price</strong></p>
            <a asp-controller="DetailsSwitch" asp-action="Details" asp-route-id="@Model.CatalogItemId">Details</a>
        }

    </div>
</div>